# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Load.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Load(object):
    def setupUi(self, Load):
        Load.setObjectName("Load")
        Load.resize(802, 505)
        self.layoutWidget = QtWidgets.QWidget(Load)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 779, 488))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadLabel_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loadLabel_1.setFont(font)
        self.loadLabel_1.setObjectName("loadLabel_1")
        self.horizontalLayout.addWidget(self.loadLabel_1)
        self.hint = QtWidgets.QPushButton(self.layoutWidget)
        self.hint.setEnabled(True)
        self.hint.setFocusPolicy(QtCore.Qt.NoFocus)
        self.hint.setText("")
        self.hint.setCheckable(False)
        self.hint.setObjectName("hint")
        self.horizontalLayout.addWidget(self.hint)
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.fileLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.fileLabel.setFont(font)
        self.fileLabel.setObjectName("fileLabel")
        self.verticalLayout_3.addWidget(self.fileLabel)
        self.filesLayout = QtWidgets.QHBoxLayout()
        self.filesLayout.setObjectName("filesLayout")
        self.verticalLayout_3.addLayout(self.filesLayout)
        spacerItem1 = QtWidgets.QSpacerItem(243, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_4.addWidget(self.lineEdit_1)
        self.Browse_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.Browse_1.setAutoDefault(True)
        self.Browse_1.setDefault(False)
        self.Browse_1.setObjectName("Browse_1")
        self.horizontalLayout_4.addWidget(self.Browse_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.Browse_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.Browse_2.setObjectName("Browse_2")
        self.horizontalLayout_5.addWidget(self.Browse_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.connectDataBaseButton = QtWidgets.QPushButton(self.layoutWidget)
        self.connectDataBaseButton.setText("")
        self.connectDataBaseButton.setCheckable(False)
        self.connectDataBaseButton.setAutoDefault(False)
        self.connectDataBaseButton.setObjectName("connectDataBaseButton")
        self.horizontalLayout_8.addWidget(self.connectDataBaseButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.loadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadButton.setObjectName("loadButton")
        self.verticalLayout.addWidget(self.loadButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem6 = QtWidgets.QSpacerItem(243, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem7 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.moleculeViewerLayout = QtWidgets.QVBoxLayout()
        self.moleculeViewerLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.moleculeViewerLayout.setSpacing(0)
        self.moleculeViewerLayout.setObjectName("moleculeViewerLayout")
        spacerItem8 = QtWidgets.QSpacerItem(295, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.moleculeViewerLayout.addItem(spacerItem8)
        self.horizontalLayout_3.addLayout(self.moleculeViewerLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.selectShowAllLayout = QtWidgets.QHBoxLayout()
        self.selectShowAllLayout.setObjectName("selectShowAllLayout")
        self.SelectAllLayout = QtWidgets.QVBoxLayout()
        self.SelectAllLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.SelectAllLayout.setObjectName("SelectAllLayout")
        self.selectShowAllLayout.addLayout(self.SelectAllLayout)
        self.ShowAllLayout = QtWidgets.QVBoxLayout()
        self.ShowAllLayout.setObjectName("ShowAllLayout")
        self.selectShowAllLayout.addLayout(self.ShowAllLayout)
        spacerItem9 = QtWidgets.QSpacerItem(598, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.selectShowAllLayout.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.selectShowAllLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(428, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.okButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_7.addWidget(self.okButton)
        spacerItem11 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setDefault(True)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_7.addWidget(self.cancelButton)
        spacerItem12 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Load)
        QtCore.QMetaObject.connectSlotsByName(Load)

    def retranslateUi(self, Load):
        _translate = QtCore.QCoreApplication.translate
        Load.setWindowTitle(_translate("Load", "Load Files"))
        self.loadLabel_1.setText(_translate("Load", "1. Load your  files.  "))
        self.fileLabel.setText(_translate("Load", "Choose files from directory. "))
        self.Browse_1.setText(_translate("Load", "Browse"))
        self.Browse_2.setText(_translate("Load", "Browse"))
        self.label.setText(_translate("Load", "-OR- "))
        self.label_2.setText(_translate("Load", "Download files from repositories."))
        self.connectDataBaseButton.setToolTip(_translate("Load", "Connect to a Data Base to load PDB or SDF files"))
        self.loadButton.setText(_translate("Load", "Load"))
        self.label_3.setText(_translate("Load", "2. Select the molecules you would like to import."))
        self.tableWidget.setToolTip(_translate("Load", "Molecules that could be isomorphic are shown with the same color."))
        self.okButton.setText(_translate("Load", "OK"))
        self.cancelButton.setText(_translate("Load", "Cancel"))

