
VERSION=0.22


all: 
	cd nanotubeEditor ; make
	cd grapheneEditor ; make
	cd homopolyEditor ; make
	cd PANI ; make
	cd PEDOT ; make
	cd PSS ; make
	cd classifier ; make
	cd main ; make
	cd celluloseEditor ; make
	cd diamondEditor ; make
	cd PANI ; make
	cd PEDOT ; make
	cd PSS ; make
	
clean:
	cd nanotubeEditor ; make clean
	cd grapheneEditor ; make clean
	cd homopolyEditor ; make clean
	cd classifier ; make clean
	cd main ; make clean

	cd celluloseEditor ; make clean
	cd diamondEditor ; make clean
	cd PANI ; make clean
	cd PEDOT ; make clean
	cd PSS ; make clean
	rm -f *.pyc *.py~ ui_*.py

