
VERSION=0.22


all: 
	cd analysis ; make
	cd chemicalGraph ; make
	cd communication ; make
	cd fbp ; make
	cd io ; make


clean:
	cd analysis ; make clean
	cd chemicalGraph ; make clean
	cd communication ; make clean
	cd io ; make clean
	rm -f *.pyc *.py~ ui_*.py

