# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Analysis.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Analysis(object):
    def setupUi(self, Analysis):
        Analysis.setObjectName("Analysis")
        Analysis.resize(693, 567)
        self.gridLayout = QtWidgets.QGridLayout(Analysis)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Analysis)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scriptLayout = QtWidgets.QVBoxLayout()
        self.scriptLayout.setObjectName("scriptLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.scriptFileName = QtWidgets.QLineEdit(self.widget)
        self.scriptFileName.setObjectName("scriptFileName")
        self.horizontalLayout.addWidget(self.scriptFileName)
        self.loadButton = QtWidgets.QPushButton(self.widget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        self.scriptLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.reloadButton = QtWidgets.QPushButton(self.widget)
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout_5.addWidget(self.reloadButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.scriptLayout.addLayout(self.horizontalLayout_5)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setEnabled(True)
        self.label_5.setAccessibleName("")
        self.label_5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_5.setObjectName("label_5")
        self.scriptLayout.addWidget(self.label_5)
        self.scriptWidget = QtWidgets.QWidget(self.widget)
        self.scriptWidget.setObjectName("scriptWidget")
        self.scriptLayout.addWidget(self.scriptWidget)
        self.verticalLayout.addLayout(self.scriptLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.runButton = QtWidgets.QPushButton(self.widget)
        self.runButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_3.addWidget(self.runButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.consoleLayout = QtWidgets.QVBoxLayout()
        self.consoleLayout.setObjectName("consoleLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.consoleLayout.addWidget(self.label_6)
        self.consoleWidget = QtWidgets.QWidget(self.widget)
        self.consoleWidget.setObjectName("consoleWidget")
        self.consoleLayout.addWidget(self.consoleWidget)
        self.verticalLayout.addLayout(self.consoleLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Analysis)
        QtCore.QMetaObject.connectSlotsByName(Analysis)

    def retranslateUi(self, Analysis):
        _translate = QtCore.QCoreApplication.translate
        Analysis.setWindowTitle(_translate("Analysis", "Dialog"))
        self.label.setText(_translate("Analysis", "Script file:"))
        self.loadButton.setText(_translate("Analysis", "Load"))
        self.reloadButton.setText(_translate("Analysis", "Reload"))
        self.label_5.setText(_translate("Analysis", "Python Script:"))
        self.runButton.setText(_translate("Analysis", "Run"))
        self.label_6.setText(_translate("Analysis", "Console:"))

