# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aboutFt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_layAboutFt(object):
    def setupUi(self, layAboutFt):
        layAboutFt.setObjectName("layAboutFt")
        layAboutFt.resize(534, 287)
        self.label = QtWidgets.QLabel(layAboutFt)
        self.label.setGeometry(QtCore.QRect(0, 10, 521, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.okB = QtWidgets.QPushButton(layAboutFt)
        self.okB.setGeometry(QtCore.QRect(420, 240, 91, 27))
        self.okB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.okB.setObjectName("okB")
        self.scrollArea = QtWidgets.QScrollArea(layAboutFt)
        self.scrollArea.setGeometry(QtCore.QRect(200, 50, 321, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.aboutSK = QtWidgets.QStackedWidget(self.scrollAreaWidgetContents)
        self.aboutSK.setGeometry(QtCore.QRect(0, 10, 311, 161))
        self.aboutSK.setObjectName("aboutSK")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(0, 40, 311, 91))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.questBEx = QtWidgets.QPushButton(self.page)
        self.questBEx.setGeometry(QtCore.QRect(130, 10, 41, 31))
        self.questBEx.setText("")
        self.questBEx.setFlat(True)
        self.questBEx.setObjectName("questBEx")
        self.aboutSK.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.saveBEx = QtWidgets.QPushButton(self.page_2)
        self.saveBEx.setGeometry(QtCore.QRect(130, 10, 41, 31))
        self.saveBEx.setText("")
        self.saveBEx.setFlat(True)
        self.saveBEx.setObjectName("saveBEx")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(0, 30, 321, 111))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.aboutSK.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.loadBEx = QtWidgets.QPushButton(self.page_3)
        self.loadBEx.setGeometry(QtCore.QRect(130, 10, 41, 31))
        self.loadBEx.setText("")
        self.loadBEx.setFlat(True)
        self.loadBEx.setObjectName("loadBEx")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 301, 71))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.aboutSK.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_2 = QtWidgets.QLabel(self.page_4)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 66, 17))
        self.label_2.setObjectName("label_2")
        self.aboutSK.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_3 = QtWidgets.QLabel(self.page_5)
        self.label_3.setGeometry(QtCore.QRect(0, 40, 311, 81))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.aboutSK.addWidget(self.page_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.saveFB = QtWidgets.QPushButton(layAboutFt)
        self.saveFB.setGeometry(QtCore.QRect(30, 50, 101, 27))
        self.saveFB.setFlat(True)
        self.saveFB.setObjectName("saveFB")
        self.loadFB = QtWidgets.QPushButton(layAboutFt)
        self.loadFB.setGeometry(QtCore.QRect(30, 80, 101, 27))
        self.loadFB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.loadFB.setAutoFillBackground(False)
        self.loadFB.setAutoDefault(True)
        self.loadFB.setDefault(False)
        self.loadFB.setFlat(True)
        self.loadFB.setObjectName("loadFB")
        self.forceTB = QtWidgets.QPushButton(layAboutFt)
        self.forceTB.setGeometry(QtCore.QRect(30, 110, 151, 27))
        self.forceTB.setAutoDefault(False)
        self.forceTB.setDefault(False)
        self.forceTB.setFlat(True)
        self.forceTB.setObjectName("forceTB")
        self.line = QtWidgets.QFrame(layAboutFt)
        self.line.setGeometry(QtCore.QRect(180, 40, 20, 201))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(layAboutFt)
        self.aboutSK.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(layAboutFt)

    def retranslateUi(self, layAboutFt):
        _translate = QtCore.QCoreApplication.translate
        layAboutFt.setWindowTitle(_translate("layAboutFt", "Dialog"))
        self.label.setText(_translate("layAboutFt", "About Force Field Tab"))
        self.okB.setText(_translate("layAboutFt", "OK"))
        self.label_6.setText(_translate("layAboutFt", "This step intends to help the user set up the\n"
" force values of the molecular system."))
        self.label_4.setText(_translate("layAboutFt", "After making changes , you can save these \n"
" changes in the selected location."))
        self.label_5.setText(_translate("layAboutFt", "Select molecule by clicking on its name \n"
"in the NONBONDED section, \n"
"identify the PRM file and you can load,\n"
" view and edit your file."))
        self.label_2.setText(_translate("layAboutFt", "hola"))
        self.label_3.setText(_translate("layAboutFt", "The table will contain the default \n"
"force fields among molecular structures."))
        self.saveFB.setText(_translate("layAboutFt", "Save PRM File"))
        self.loadFB.setText(_translate("layAboutFt", "Load PRM File"))
        self.forceTB.setText(_translate("layAboutFt", "Set Force Fields Table"))

