# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CHARMMParameterFinderDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CHARMMParameterFinderDialog(object):
    def setupUi(self, CHARMMParameterFinderDialog):
        CHARMMParameterFinderDialog.setObjectName("CHARMMParameterFinderDialog")
        CHARMMParameterFinderDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        CHARMMParameterFinderDialog.resize(645, 554)
        self.verticalLayoutWidget = QtWidgets.QWidget(CHARMMParameterFinderDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 621, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.collectionsListWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.collectionsListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.collectionsListWidget.setObjectName("collectionsListWidget")
        item = QtWidgets.QListWidgetItem()
        self.collectionsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.collectionsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.collectionsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.collectionsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.collectionsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.collectionsListWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.collectionsListWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.hydrogensCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.hydrogensCheckBox.setCheckable(True)
        self.hydrogensCheckBox.setChecked(True)
        self.hydrogensCheckBox.setObjectName("hydrogensCheckBox")
        self.horizontalLayout_2.addWidget(self.hydrogensCheckBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.timeLimitSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.timeLimitSlider.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.timeLimitSlider.setMinimum(5)
        self.timeLimitSlider.setMaximum(3000)
        self.timeLimitSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeLimitSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.timeLimitSlider.setTickInterval(10)
        self.timeLimitSlider.setObjectName("timeLimitSlider")
        self.horizontalLayout_12.addWidget(self.timeLimitSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.timeLeftClock = QwtAnalogClock(self.verticalLayoutWidget)
        self.timeLeftClock.setMaximumSize(QtCore.QSize(16777215, 125))
        self.timeLeftClock.setProperty("lineWidth", 4)
        self.timeLeftClock.setObjectName("timeLeftClock")
        self.verticalLayout_5.addWidget(self.timeLeftClock)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.reportTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.reportTextEdit.setMaximumSize(QtCore.QSize(16777215, 125))
        self.reportTextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.reportTextEdit.setObjectName("reportTextEdit")
        self.verticalLayout_6.addWidget(self.reportTextEdit)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.startButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_4.addWidget(self.startButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.acceptButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_8.addWidget(self.acceptButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.rejectButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.rejectButton.setObjectName("rejectButton")
        self.horizontalLayout_8.addWidget(self.rejectButton)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(CHARMMParameterFinderDialog)
        self.collectionsListWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(CHARMMParameterFinderDialog)

    def retranslateUi(self, CHARMMParameterFinderDialog):
        _translate = QtCore.QCoreApplication.translate
        CHARMMParameterFinderDialog.setWindowTitle(_translate("CHARMMParameterFinderDialog", "CHARMM parameter finder"))
        self.label_4.setText(_translate("CHARMMParameterFinderDialog", "CHARMM Parameter Finder"))
        self.label.setText(_translate("CHARMMParameterFinderDialog", "Select collections"))
        __sortingEnabled = self.collectionsListWidget.isSortingEnabled()
        self.collectionsListWidget.setSortingEnabled(False)
        item = self.collectionsListWidget.item(0)
        item.setText(_translate("CHARMMParameterFinderDialog", "All-Hydrogen Lipid"))
        item = self.collectionsListWidget.item(1)
        item.setText(_translate("CHARMMParameterFinderDialog", "All-hydrogen ether"))
        item = self.collectionsListWidget.item(2)
        item.setText(_translate("CHARMMParameterFinderDialog", "All-hydrogen carbohydrate"))
        item = self.collectionsListWidget.item(3)
        item.setText(_translate("CHARMMParameterFinderDialog", "All-Hydrogen Proteins"))
        item = self.collectionsListWidget.item(4)
        item.setText(_translate("CHARMMParameterFinderDialog", "Silicates"))
        item = self.collectionsListWidget.item(5)
        item.setText(_translate("CHARMMParameterFinderDialog", "General Force Field"))
        self.collectionsListWidget.setSortingEnabled(__sortingEnabled)
        self.hydrogensCheckBox.setText(_translate("CHARMMParameterFinderDialog", "include hydrogens"))
        self.label_9.setText(_translate("CHARMMParameterFinderDialog", "Time limit:"))
        self.label_7.setText(_translate("CHARMMParameterFinderDialog", "time left"))
        self.label_8.setText(_translate("CHARMMParameterFinderDialog", "matches"))
        self.startButton.setText(_translate("CHARMMParameterFinderDialog", "Start"))
        self.acceptButton.setText(_translate("CHARMMParameterFinderDialog", "Accept"))
        self.rejectButton.setText(_translate("CHARMMParameterFinderDialog", "Reject"))

from PyQt5.Qwt5 import QwtAnalogClock
