# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertyEditor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_propertyEditor(object):
    def setupUi(self, propertyEditor):
        propertyEditor.setObjectName("propertyEditor")
        propertyEditor.resize(214, 192)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(propertyEditor.sizePolicy().hasHeightForWidth())
        propertyEditor.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(propertyEditor)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.propertyTree = QtWidgets.QTreeWidget(propertyEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyTree.sizePolicy().hasHeightForWidth())
        self.propertyTree.setSizePolicy(sizePolicy)
        self.propertyTree.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.propertyTree.setFont(font)
        self.propertyTree.setAutoScroll(True)
        self.propertyTree.setProperty("showDropIndicator", False)
        self.propertyTree.setAlternatingRowColors(True)
        self.propertyTree.setUniformRowHeights(True)
        self.propertyTree.setAllColumnsShowFocus(False)
        self.propertyTree.setWordWrap(True)
        self.propertyTree.setObjectName("propertyTree")
        self.propertyTree.headerItem().setText(0, "Property")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.propertyTree.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.propertyTree.headerItem().setFont(1, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.propertyTree)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_0 = QtWidgets.QTreeWidgetItem(self.propertyTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.propertyTree)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.propertyTree)
        item_0.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsEnabled)
        self.propertyTree.header().setCascadingSectionResizes(False)
        self.gridLayout.addWidget(self.propertyTree, 0, 0, 1, 1)

        self.retranslateUi(propertyEditor)
        QtCore.QMetaObject.connectSlotsByName(propertyEditor)

    def retranslateUi(self, propertyEditor):
        _translate = QtCore.QCoreApplication.translate
        propertyEditor.setWindowTitle(_translate("propertyEditor", "Form"))
        self.propertyTree.setSortingEnabled(False)
        self.propertyTree.headerItem().setText(1, _translate("propertyEditor", "Value"))
        __sortingEnabled = self.propertyTree.isSortingEnabled()
        self.propertyTree.setSortingEnabled(False)
        self.propertyTree.topLevelItem(0).setText(0, _translate("propertyEditor", "Name"))
        self.propertyTree.topLevelItem(1).setText(0, _translate("propertyEditor", "Rotate by     "))
        self.propertyTree.topLevelItem(1).child(0).setText(0, _translate("propertyEditor", "X"))
        self.propertyTree.topLevelItem(1).child(1).setText(0, _translate("propertyEditor", "Y"))
        self.propertyTree.topLevelItem(1).child(2).setText(0, _translate("propertyEditor", "Z"))
        self.propertyTree.topLevelItem(2).setText(0, _translate("propertyEditor", "Move by"))
        self.propertyTree.topLevelItem(2).child(0).setText(0, _translate("propertyEditor", "X"))
        self.propertyTree.topLevelItem(2).child(1).setText(0, _translate("propertyEditor", "Y"))
        self.propertyTree.topLevelItem(2).child(2).setText(0, _translate("propertyEditor", "Z"))
        self.propertyTree.topLevelItem(3).setText(0, _translate("propertyEditor", "Comment"))
        self.propertyTree.setSortingEnabled(__sortingEnabled)

