# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.setEnabled(True)
        settingsDialog.resize(390, 550)
        settingsDialog.setMinimumSize(QtCore.QSize(390, 550))
        settingsDialog.setMaximumSize(QtCore.QSize(400, 600))
        self.groupBox = QtWidgets.QGroupBox(settingsDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 371, 241))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.defDirLabel = QtWidgets.QLabel(self.groupBox)
        self.defDirLabel.setObjectName("defDirLabel")
        self.gridLayout_4.addWidget(self.defDirLabel, 0, 0, 1, 2)
        self.defDirLine = QtWidgets.QLineEdit(self.groupBox)
        self.defDirLine.setMinimumSize(QtCore.QSize(125, 0))
        self.defDirLine.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.defDirLine.setReadOnly(True)
        self.defDirLine.setObjectName("defDirLine")
        self.gridLayout_4.addWidget(self.defDirLine, 1, 0, 1, 2)
        self.defDirButton = QtWidgets.QPushButton(self.groupBox)
        self.defDirButton.setObjectName("defDirButton")
        self.gridLayout_4.addWidget(self.defDirButton, 1, 3, 1, 1)
        self.resetButton = QtWidgets.QToolButton(self.groupBox)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_4.addWidget(self.resetButton, 1, 2, 1, 1)
        self.namD = QtWidgets.QRadioButton(self.groupBox)
        self.namD.setObjectName("namD")
        self.gridLayout_4.addWidget(self.namD, 3, 0, 1, 1)
        self.NAMDloc = QtWidgets.QLabel(self.groupBox)
        self.NAMDloc.setObjectName("NAMDloc")
        self.gridLayout_4.addWidget(self.NAMDloc, 4, 0, 1, 2)
        self.skinsL = QtWidgets.QLabel(self.groupBox)
        self.skinsL.setObjectName("skinsL")
        self.gridLayout_4.addWidget(self.skinsL, 6, 0, 1, 1)
        self.defMDPlaceLabel = QtWidgets.QLineEdit(self.groupBox)
        self.defMDPlaceLabel.setEnabled(True)
        self.defMDPlaceLabel.setToolTip("")
        self.defMDPlaceLabel.setReadOnly(True)
        self.defMDPlaceLabel.setObjectName("defMDPlaceLabel")
        self.gridLayout_4.addWidget(self.defMDPlaceLabel, 5, 0, 1, 2)
        self.defMDPlaceButton = QtWidgets.QPushButton(self.groupBox)
        self.defMDPlaceButton.setObjectName("defMDPlaceButton")
        self.gridLayout_4.addWidget(self.defMDPlaceButton, 5, 3, 1, 1)
        self.resetMDButton = QtWidgets.QToolButton(self.groupBox)
        self.resetMDButton.setObjectName("resetMDButton")
        self.gridLayout_4.addWidget(self.resetMDButton, 5, 2, 1, 1)
        self.gromacs = QtWidgets.QRadioButton(self.groupBox)
        self.gromacs.setEnabled(True)
        self.gromacs.setObjectName("gromacs")
        self.gridLayout_4.addWidget(self.gromacs, 3, 1, 1, 2)
        self.options = QtWidgets.QLineEdit(self.groupBox)
        self.options.setObjectName("options")
        self.gridLayout_4.addWidget(self.options, 6, 1, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(settingsDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 400, 241, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.version = QtWidgets.QLabel(self.groupBox_3)
        self.version.setStyleSheet("font: 75 italic 11pt \"Ubuntu\";\n"
"text-decoration: underline;")
        self.version.setObjectName("version")
        self.gridLayout_3.addWidget(self.version, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setTextFormat(QtCore.Qt.RichText)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setIndent(-1)
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 1, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(settingsDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 361, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.highResolutionButton = QtWidgets.QCheckBox(self.groupBox_2)
        self.highResolutionButton.setObjectName("highResolutionButton")
        self.gridLayout_2.addWidget(self.highResolutionButton, 1, 1, 1, 1)
        self.viewHelpcheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.viewHelpcheckBox.setObjectName("viewHelpcheckBox")
        self.gridLayout_2.addWidget(self.viewHelpcheckBox, 3, 0, 1, 1)
        self.labelsCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.labelsCheckBox.setEnabled(True)
        self.labelsCheckBox.setObjectName("labelsCheckBox")
        self.gridLayout_2.addWidget(self.labelsCheckBox, 1, 0, 1, 1)
        self.axesCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.axesCheckBox.setObjectName("axesCheckBox")
        self.gridLayout_2.addWidget(self.axesCheckBox, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.solventHighResolutionButton = QtWidgets.QCheckBox(self.groupBox_2)
        self.solventHighResolutionButton.setObjectName("solventHighResolutionButton")
        self.gridLayout_2.addWidget(self.solventHighResolutionButton, 3, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(settingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 520, 161, 25))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(settingsDialog)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Change Settings"))
        self.groupBox.setTitle(_translate("settingsDialog", "Customization"))
        self.label.setText(_translate("settingsDialog", "MD Package:"))
        self.defDirLabel.setText(_translate("settingsDialog", "Working Folder: "))
        self.defDirButton.setToolTip(_translate("settingsDialog", "Change Directory"))
        self.defDirButton.setText(_translate("settingsDialog", "Change"))
        self.resetButton.setToolTip(_translate("settingsDialog", "Reset to Default Settings"))
        self.resetButton.setText(_translate("settingsDialog", "..."))
        self.namD.setText(_translate("settingsDialog", "NAMD"))
        self.NAMDloc.setText(_translate("settingsDialog", "NAMD Location: "))
        self.skinsL.setText(_translate("settingsDialog", "Options: "))
        self.defMDPlaceButton.setToolTip(_translate("settingsDialog", "Change Executable"))
        self.defMDPlaceButton.setText(_translate("settingsDialog", "Change"))
        self.resetMDButton.setToolTip(_translate("settingsDialog", "Searches for MD package on sistem"))
        self.resetMDButton.setText(_translate("settingsDialog", "..."))
        self.gromacs.setText(_translate("settingsDialog", "GROMACS"))
        self.groupBox_3.setTitle(_translate("settingsDialog", "About"))
        self.label_4.setText(_translate("settingsDialog", "Version:"))
        self.version.setText(_translate("settingsDialog", "0.22"))
        self.label_6.setText(_translate("settingsDialog", "Website: "))
        self.label_3.setText(_translate("settingsDialog", "Legal:"))
        self.label_8.setText(_translate("settingsDialog", "<html><head/><body><p><a href=\"http://wolffia.uprh.edu/\"><span style=\" text-decoration: underline; color:#0000ff;\">wolffia.uprh.edu</span></a></p></body></html>"))
        self.groupBox_2.setTitle(_translate("settingsDialog", "Graphics"))
        self.highResolutionButton.setText(_translate("settingsDialog", "Molecules"))
        self.viewHelpcheckBox.setText(_translate("settingsDialog", "Help"))
        self.labelsCheckBox.setText(_translate("settingsDialog", "Atom Labels"))
        self.axesCheckBox.setText(_translate("settingsDialog", "Axes"))
        self.label_2.setText(_translate("settingsDialog", "High resolution:"))
        self.label_5.setText(_translate("settingsDialog", "View:"))
        self.solventHighResolutionButton.setText(_translate("settingsDialog", "Solvent"))

