# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solventDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_solventDialog(object):
    def setupUi(self, solventDialog):
        solventDialog.setObjectName("solventDialog")
        solventDialog.setEnabled(True)
        solventDialog.resize(402, 442)
        self.gridLayout = QtWidgets.QGridLayout(solventDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_13 = QtWidgets.QLabel(solventDialog)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.solventComboBox = QtWidgets.QComboBox(solventDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.solventComboBox.setFont(font)
        self.solventComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.solventComboBox.setObjectName("solventComboBox")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.horizontalLayout_10.addWidget(self.solventComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.announce = QtWidgets.QLabel(solventDialog)
        self.announce.setWordWrap(True)
        self.announce.setObjectName("announce")
        self.horizontalLayout.addWidget(self.announce)
        self.molBox = QtWidgets.QSpinBox(solventDialog)
        self.molBox.setMaximumSize(QtCore.QSize(125, 16777215))
        self.molBox.setMaximum(100000)
        self.molBox.setObjectName("molBox")
        self.horizontalLayout.addWidget(self.molBox)
        self.label_3 = QtWidgets.QLabel(solventDialog)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(solventDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.densitySpinBox = QtWidgets.QDoubleSpinBox(solventDialog)
        self.densitySpinBox.setMaximumSize(QtCore.QSize(125, 16777215))
        self.densitySpinBox.setDecimals(4)
        self.densitySpinBox.setMaximum(99999.0)
        self.densitySpinBox.setSingleStep(0.1)
        self.densitySpinBox.setObjectName("densitySpinBox")
        self.horizontalLayout_2.addWidget(self.densitySpinBox)
        self.label_2 = QtWidgets.QLabel(solventDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(75, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(solventDialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.volLineEdit = QtWidgets.QLineEdit(solventDialog)
        self.volLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volLineEdit.sizePolicy().hasHeightForWidth())
        self.volLineEdit.setSizePolicy(sizePolicy)
        self.volLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.volLineEdit.setMaximumSize(QtCore.QSize(125, 16777215))
        self.volLineEdit.setReadOnly(True)
        self.volLineEdit.setObjectName("volLineEdit")
        self.horizontalLayout_3.addWidget(self.volLineEdit)
        self.label_15 = QtWidgets.QLabel(solventDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(30, 0))
        self.label_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.line_3 = QtWidgets.QFrame(solventDialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.line_6 = QtWidgets.QFrame(solventDialog)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.cancelButton = QtWidgets.QPushButton(solventDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_9.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(solventDialog)
        self.okButton.setDefault(True)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_9.addWidget(self.okButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.retranslateUi(solventDialog)
        self.solventComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(solventDialog)

    def retranslateUi(self, solventDialog):
        _translate = QtCore.QCoreApplication.translate
        solventDialog.setWindowTitle(_translate("solventDialog", "Solvating the System"))
        self.label_13.setText(_translate("solventDialog", "Fill container with"))
        self.solventComboBox.setItemText(0, _translate("solventDialog", "Water"))
        self.solventComboBox.setItemText(1, _translate("solventDialog", "Acetone"))
        self.solventComboBox.setItemText(2, _translate("solventDialog", "Chloroform"))
        self.solventComboBox.setItemText(3, _translate("solventDialog", "Chloroform (4 atoms)"))
        self.solventComboBox.setItemText(4, _translate("solventDialog", "THF"))
        self.solventComboBox.setItemText(5, _translate("solventDialog", "Argon"))
        self.announce.setText(_translate("solventDialog", "Solvent: "))
        self.label_3.setText(_translate("solventDialog", "molecules"))
        self.label.setText(_translate("solventDialog", "Density:"))
        self.label_2.setText(_translate("solventDialog", "g/cm<sup>3</sup>"))
        self.label_9.setText(_translate("solventDialog", "Volume"))
        self.label_15.setText(_translate("solventDialog", "nm<sup>3</sup>"))
        self.cancelButton.setText(_translate("solventDialog", "Cancel"))
        self.okButton.setText(_translate("solventDialog", "Ok"))

import Wolffia_icons_rc
