# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setupTab.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_setupTab(object):
    def setupUi(self, setupTab):
        setupTab.setObjectName("setupTab")
        setupTab.resize(785, 582)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(setupTab.sizePolicy().hasHeightForWidth())
        setupTab.setSizePolicy(sizePolicy)
        setupTab.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(setupTab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtWidgets.QLabel(setupTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.boundLayout_2 = QtWidgets.QHBoxLayout()
        self.boundLayout_2.setObjectName("boundLayout_2")
        self.boxBoundButton = QtWidgets.QRadioButton(setupTab)
        self.boxBoundButton.setObjectName("boxBoundButton")
        self.boundLayout_2.addWidget(self.boxBoundButton)
        self.noneRButton = QtWidgets.QRadioButton(setupTab)
        self.noneRButton.setCheckable(True)
        self.noneRButton.setChecked(True)
        self.noneRButton.setObjectName("noneRButton")
        self.boundLayout_2.addWidget(self.noneRButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.boundLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.boundLayout_2)
        self.line_10 = QtWidgets.QFrame(setupTab)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_5.addWidget(self.line_10)
        self.boundStackedWidget = QtWidgets.QStackedWidget(setupTab)
        self.boundStackedWidget.setEnabled(True)
        self.boundStackedWidget.setObjectName("boundStackedWidget")
        self.boxPage = QtWidgets.QWidget()
        self.boxPage.setEnabled(True)
        self.boxPage.setObjectName("boxPage")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.boxPage)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.boxPage)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 755, 480))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.editToolbox = QtWidgets.QToolBox(self.scrollAreaWidgetContents_2)
        self.editToolbox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editToolbox.sizePolicy().hasHeightForWidth())
        self.editToolbox.setSizePolicy(sizePolicy)
        self.editToolbox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(True)
        self.editToolbox.setFont(font)
        self.editToolbox.setObjectName("editToolbox")
        self.editBoxPage = QtWidgets.QWidget()
        self.editBoxPage.setGeometry(QtCore.QRect(0, 0, 755, 378))
        self.editBoxPage.setObjectName("editBoxPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.editBoxPage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.resizeLabel_3 = QtWidgets.QLabel(self.editBoxPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resizeLabel_3.setFont(font)
        self.resizeLabel_3.setObjectName("resizeLabel_3")
        self.verticalLayout_24.addWidget(self.resizeLabel_3)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ratioPCheckBox = QtWidgets.QCheckBox(self.editBoxPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.ratioPCheckBox.setFont(font)
        self.ratioPCheckBox.setChecked(False)
        self.ratioPCheckBox.setObjectName("ratioPCheckBox")
        self.horizontalLayout_5.addWidget(self.ratioPCheckBox)
        self.equalCheckBox = QtWidgets.QCheckBox(self.editBoxPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.equalCheckBox.setFont(font)
        self.equalCheckBox.setObjectName("equalCheckBox")
        self.horizontalLayout_5.addWidget(self.equalCheckBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_25.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.lengthLabel_2 = QtWidgets.QLabel(self.editBoxPage)
        self.lengthLabel_2.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.lengthLabel_2.setFont(font)
        self.lengthLabel_2.setObjectName("lengthLabel_2")
        self.horizontalLayout_11.addWidget(self.lengthLabel_2)
        self.lengthSlider = QtWidgets.QSlider(self.editBoxPage)
        self.lengthSlider.setEnabled(True)
        self.lengthSlider.setMaximum(1000)
        self.lengthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lengthSlider.setObjectName("lengthSlider")
        self.horizontalLayout_11.addWidget(self.lengthSlider)
        self.lengthDSpinner = QtWidgets.QDoubleSpinBox(self.editBoxPage)
        self.lengthDSpinner.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.lengthDSpinner.setFont(font)
        self.lengthDSpinner.setDecimals(3)
        self.lengthDSpinner.setMinimum(1.0)
        self.lengthDSpinner.setMaximum(1000.0)
        self.lengthDSpinner.setSingleStep(1.0)
        self.lengthDSpinner.setObjectName("lengthDSpinner")
        self.horizontalLayout_11.addWidget(self.lengthDSpinner)
        self.verticalLayout_25.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem4)
        self.widthLabel_2 = QtWidgets.QLabel(self.editBoxPage)
        self.widthLabel_2.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.widthLabel_2.setFont(font)
        self.widthLabel_2.setObjectName("widthLabel_2")
        self.horizontalLayout_16.addWidget(self.widthLabel_2)
        self.widthSlider = QtWidgets.QSlider(self.editBoxPage)
        self.widthSlider.setEnabled(False)
        self.widthSlider.setMaximum(1000)
        self.widthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.widthSlider.setObjectName("widthSlider")
        self.horizontalLayout_16.addWidget(self.widthSlider)
        self.widthDSpinner = QtWidgets.QDoubleSpinBox(self.editBoxPage)
        self.widthDSpinner.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(False)
        self.widthDSpinner.setFont(font)
        self.widthDSpinner.setDecimals(3)
        self.widthDSpinner.setMinimum(1.0)
        self.widthDSpinner.setMaximum(1000.0)
        self.widthDSpinner.setObjectName("widthDSpinner")
        self.horizontalLayout_16.addWidget(self.widthDSpinner)
        self.verticalLayout_25.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem5)
        self.heightLabel_2 = QtWidgets.QLabel(self.editBoxPage)
        self.heightLabel_2.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.heightLabel_2.setFont(font)
        self.heightLabel_2.setObjectName("heightLabel_2")
        self.horizontalLayout_17.addWidget(self.heightLabel_2)
        self.heightSlider = QtWidgets.QSlider(self.editBoxPage)
        self.heightSlider.setEnabled(False)
        self.heightSlider.setMaximum(1000)
        self.heightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.heightSlider.setObjectName("heightSlider")
        self.horizontalLayout_17.addWidget(self.heightSlider)
        self.heightDSpinner = QtWidgets.QDoubleSpinBox(self.editBoxPage)
        self.heightDSpinner.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(False)
        self.heightDSpinner.setFont(font)
        self.heightDSpinner.setDecimals(3)
        self.heightDSpinner.setMinimum(1.0)
        self.heightDSpinner.setMaximum(1000.0)
        self.heightDSpinner.setObjectName("heightDSpinner")
        self.horizontalLayout_17.addWidget(self.heightDSpinner)
        self.verticalLayout_25.addLayout(self.horizontalLayout_17)
        self.verticalLayout_24.addLayout(self.verticalLayout_25)
        self.line_5 = QtWidgets.QFrame(self.editBoxPage)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_24.addWidget(self.line_5)
        self.movePerLabel_3 = QtWidgets.QLabel(self.editBoxPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.movePerLabel_3.setFont(font)
        self.movePerLabel_3.setObjectName("movePerLabel_3")
        self.verticalLayout_24.addWidget(self.movePerLabel_3)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem6)
        self.perXLabel_2 = QtWidgets.QLabel(self.editBoxPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perXLabel_2.sizePolicy().hasHeightForWidth())
        self.perXLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.perXLabel_2.setFont(font)
        self.perXLabel_2.setObjectName("perXLabel_2")
        self.horizontalLayout_59.addWidget(self.perXLabel_2)
        self.perXSpinner = QtWidgets.QDoubleSpinBox(self.editBoxPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perXSpinner.sizePolicy().hasHeightForWidth())
        self.perXSpinner.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.perXSpinner.setFont(font)
        self.perXSpinner.setMinimum(-10000.0)
        self.perXSpinner.setMaximum(10000.0)
        self.perXSpinner.setObjectName("perXSpinner")
        self.horizontalLayout_59.addWidget(self.perXSpinner)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem7)
        self.perYLabel_2 = QtWidgets.QLabel(self.editBoxPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.perYLabel_2.setFont(font)
        self.perYLabel_2.setObjectName("perYLabel_2")
        self.horizontalLayout_59.addWidget(self.perYLabel_2)
        self.perYSpinner = QtWidgets.QDoubleSpinBox(self.editBoxPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.perYSpinner.setFont(font)
        self.perYSpinner.setMinimum(-10000.0)
        self.perYSpinner.setMaximum(10000.0)
        self.perYSpinner.setObjectName("perYSpinner")
        self.horizontalLayout_59.addWidget(self.perYSpinner)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem8)
        self.perZLabel_2 = QtWidgets.QLabel(self.editBoxPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perZLabel_2.sizePolicy().hasHeightForWidth())
        self.perZLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.perZLabel_2.setFont(font)
        self.perZLabel_2.setObjectName("perZLabel_2")
        self.horizontalLayout_59.addWidget(self.perZLabel_2)
        self.perZSpinner = QtWidgets.QDoubleSpinBox(self.editBoxPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perZSpinner.sizePolicy().hasHeightForWidth())
        self.perZSpinner.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.perZSpinner.setFont(font)
        self.perZSpinner.setMinimum(-10000.0)
        self.perZSpinner.setMaximum(10000.0)
        self.perZSpinner.setObjectName("perZSpinner")
        self.horizontalLayout_59.addWidget(self.perZSpinner)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem9)
        self.verticalLayout_24.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem10)
        self.setMinBoxButton = QtWidgets.QPushButton(self.editBoxPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.setMinBoxButton.setFont(font)
        self.setMinBoxButton.setAutoDefault(False)
        self.setMinBoxButton.setObjectName("setMinBoxButton")
        self.horizontalLayout_60.addWidget(self.setMinBoxButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_60.addItem(spacerItem11)
        self.verticalLayout_24.addLayout(self.horizontalLayout_60)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem12)
        self.verticalLayout_6.addLayout(self.verticalLayout_24)
        self.editToolbox.addItem(self.editBoxPage, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 755, 378))
        self.page_5.setMinimumSize(QtCore.QSize(0, 0))
        self.page_5.setObjectName("page_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_24 = QtWidgets.QLabel(self.page_5)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_22.addWidget(self.label_24)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem13)
        self.solventComboBox = QtWidgets.QComboBox(self.page_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.solventComboBox.setFont(font)
        self.solventComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.solventComboBox.setObjectName("solventComboBox")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.solventComboBox.addItem("")
        self.horizontalLayout_22.addWidget(self.solventComboBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_18 = QtWidgets.QLabel(self.page_5)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_30.addWidget(self.label_18)
        self.molBox = QtWidgets.QSpinBox(self.page_5)
        self.molBox.setMaximumSize(QtCore.QSize(125, 16777215))
        self.molBox.setMinimum(1)
        self.molBox.setMaximum(1000000)
        self.molBox.setObjectName("molBox")
        self.horizontalLayout_30.addWidget(self.molBox)
        self.label_23 = QtWidgets.QLabel(self.page_5)
        self.label_23.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_30.addWidget(self.label_23)
        self.verticalLayout_10.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_12 = QtWidgets.QLabel(self.page_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_23.addWidget(self.label_12)
        self.densitySpinBox = QtWidgets.QDoubleSpinBox(self.page_5)
        self.densitySpinBox.setMaximumSize(QtCore.QSize(125, 16777215))
        self.densitySpinBox.setDecimals(4)
        self.densitySpinBox.setMaximum(99999.0)
        self.densitySpinBox.setSingleStep(0.1)
        self.densitySpinBox.setObjectName("densitySpinBox")
        self.horizontalLayout_23.addWidget(self.densitySpinBox)
        self.label_19 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(75, 0))
        self.label_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_23.addWidget(self.label_19)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_20 = QtWidgets.QLabel(self.page_5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_24.addWidget(self.label_20)
        self.volLineEdit = QtWidgets.QLineEdit(self.page_5)
        self.volLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volLineEdit.sizePolicy().hasHeightForWidth())
        self.volLineEdit.setSizePolicy(sizePolicy)
        self.volLineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.volLineEdit.setMaximumSize(QtCore.QSize(125, 16777215))
        self.volLineEdit.setReadOnly(True)
        self.volLineEdit.setObjectName("volLineEdit")
        self.horizontalLayout_24.addWidget(self.volLineEdit)
        self.label_21 = QtWidgets.QLabel(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(30, 0))
        self.label_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.collisionsBox = QtWidgets.QCheckBox(self.page_5)
        self.collisionsBox.setMaximumSize(QtCore.QSize(225, 16777215))
        self.collisionsBox.setChecked(True)
        self.collisionsBox.setObjectName("collisionsBox")
        self.horizontalLayout.addWidget(self.collisionsBox)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.replaceCheckBox = QtWidgets.QCheckBox(self.page_5)
        self.replaceCheckBox.setObjectName("replaceCheckBox")
        self.horizontalLayout_3.addWidget(self.replaceCheckBox)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pcbBox = QtWidgets.QCheckBox(self.page_5)
        self.pcbBox.setChecked(True)
        self.pcbBox.setObjectName("pcbBox")
        self.horizontalLayout_4.addWidget(self.pcbBox)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem17)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem18)
        self.removeButton = QtWidgets.QPushButton(self.page_5)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_25.addWidget(self.removeButton)
        self.addButton = QtWidgets.QPushButton(self.page_5)
        self.addButton.setDefault(True)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_25.addWidget(self.addButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_25)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem19)
        self.editToolbox.addItem(self.page_5, "")
        self.advBoxPage = QtWidgets.QWidget()
        self.advBoxPage.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.advBoxPage.setObjectName("advBoxPage")
        self.layoutWidget = QtWidgets.QWidget(self.advBoxPage)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 60, 163, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_86 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_86.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_86.setObjectName("horizontalLayout_86")
        self.hydrogenBonding = QtWidgets.QCheckBox(self.layoutWidget)
        self.hydrogenBonding.setEnabled(True)
        self.hydrogenBonding.setChecked(False)
        self.hydrogenBonding.setObjectName("hydrogenBonding")
        self.horizontalLayout_86.addWidget(self.hydrogenBonding)
        self.layoutWidget1 = QtWidgets.QWidget(self.advBoxPage)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 158, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_84.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.waterWrap = QtWidgets.QCheckBox(self.layoutWidget1)
        self.waterWrap.setChecked(False)
        self.waterWrap.setObjectName("waterWrap")
        self.horizontalLayout_84.addWidget(self.waterWrap)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_84.addItem(spacerItem20)
        self.layoutWidget2 = QtWidgets.QWidget(self.advBoxPage)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 30, 161, 24))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_85 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_85.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_85.setObjectName("horizontalLayout_85")
        self.wrapAllMolecules = QtWidgets.QCheckBox(self.advBoxPage)
        self.wrapAllMolecules.setEnabled(True)
        self.wrapAllMolecules.setGeometry(QtCore.QRect(0, 30, 154, 22))
        self.wrapAllMolecules.setChecked(False)
        self.wrapAllMolecules.setObjectName("wrapAllMolecules")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.advBoxPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 90, 761, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem21)
        self.editToolbox.addItem(self.advBoxPage, "")
        self.verticalLayout_3.addWidget(self.editToolbox)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_20.addWidget(self.scrollArea_2)
        self.boundStackedWidget.addWidget(self.boxPage)
        self.npPage = QtWidgets.QWidget()
        self.npPage.setObjectName("npPage")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.npPage)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.sphereToolBox = QtWidgets.QToolBox(self.npPage)
        self.sphereToolBox.setEnabled(True)
        self.sphereToolBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(True)
        self.sphereToolBox.setFont(font)
        self.sphereToolBox.setObjectName("sphereToolBox")
        self.spheEditPage = QtWidgets.QWidget()
        self.spheEditPage.setGeometry(QtCore.QRect(0, 0, 320, 392))
        self.spheEditPage.setObjectName("spheEditPage")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.spheEditPage)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.label_5 = QtWidgets.QLabel(self.spheEditPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_48.addWidget(self.label_5)
        self.horizontalLayout_105 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_105.setObjectName("horizontalLayout_105")
        spacerItem22 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_105.addItem(spacerItem22)
        self.spheRButton_2 = QtWidgets.QRadioButton(self.spheEditPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.spheRButton_2.setFont(font)
        self.spheRButton_2.setChecked(True)
        self.spheRButton_2.setObjectName("spheRButton_2")
        self.horizontalLayout_105.addWidget(self.spheRButton_2)
        self.cylRButton_2 = QtWidgets.QRadioButton(self.spheEditPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylRButton_2.setFont(font)
        self.cylRButton_2.setObjectName("cylRButton_2")
        self.horizontalLayout_105.addWidget(self.cylRButton_2)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_105.addItem(spacerItem23)
        self.verticalLayout_48.addLayout(self.horizontalLayout_105)
        self.line_11 = QtWidgets.QFrame(self.spheEditPage)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_48.addWidget(self.line_11)
        self.NPResizeLabel_2 = QtWidgets.QLabel(self.spheEditPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NPResizeLabel_2.setFont(font)
        self.NPResizeLabel_2.setObjectName("NPResizeLabel_2")
        self.verticalLayout_48.addWidget(self.NPResizeLabel_2)
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ratioNPCheckBox_2 = QtWidgets.QCheckBox(self.spheEditPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.ratioNPCheckBox_2.setFont(font)
        self.ratioNPCheckBox_2.setChecked(True)
        self.ratioNPCheckBox_2.setObjectName("ratioNPCheckBox_2")
        self.horizontalLayout_8.addWidget(self.ratioNPCheckBox_2)
        spacerItem24 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem24)
        self.verticalLayout_49.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem25 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem25)
        self.centerLabel_2 = QtWidgets.QLabel(self.spheEditPage)
        self.centerLabel_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.centerLabel_2.setFont(font)
        self.centerLabel_2.setObjectName("centerLabel_2")
        self.horizontalLayout_27.addWidget(self.centerLabel_2)
        self.centerXSpinner_2 = QtWidgets.QDoubleSpinBox(self.spheEditPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerXSpinner_2.sizePolicy().hasHeightForWidth())
        self.centerXSpinner_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.centerXSpinner_2.setFont(font)
        self.centerXSpinner_2.setObjectName("centerXSpinner_2")
        self.horizontalLayout_27.addWidget(self.centerXSpinner_2)
        self.centerYSpinner_2 = QtWidgets.QDoubleSpinBox(self.spheEditPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerYSpinner_2.sizePolicy().hasHeightForWidth())
        self.centerYSpinner_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.centerYSpinner_2.setFont(font)
        self.centerYSpinner_2.setObjectName("centerYSpinner_2")
        self.horizontalLayout_27.addWidget(self.centerYSpinner_2)
        self.centerDSpinner_2 = QtWidgets.QDoubleSpinBox(self.spheEditPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centerDSpinner_2.sizePolicy().hasHeightForWidth())
        self.centerDSpinner_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.centerDSpinner_2.setFont(font)
        self.centerDSpinner_2.setObjectName("centerDSpinner_2")
        self.horizontalLayout_27.addWidget(self.centerDSpinner_2)
        self.verticalLayout_49.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem26 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem26)
        self.radiusLabel_2 = QtWidgets.QLabel(self.spheEditPage)
        self.radiusLabel_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.radiusLabel_2.setFont(font)
        self.radiusLabel_2.setObjectName("radiusLabel_2")
        self.horizontalLayout_28.addWidget(self.radiusLabel_2)
        self.radiusSlider_2 = QtWidgets.QSlider(self.spheEditPage)
        self.radiusSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.radiusSlider_2.setObjectName("radiusSlider_2")
        self.horizontalLayout_28.addWidget(self.radiusSlider_2)
        self.radiusDSpinner_2 = QtWidgets.QDoubleSpinBox(self.spheEditPage)
        font = QtGui.QFont()
        font.setItalic(False)
        self.radiusDSpinner_2.setFont(font)
        self.radiusDSpinner_2.setObjectName("radiusDSpinner_2")
        self.horizontalLayout_28.addWidget(self.radiusDSpinner_2)
        self.verticalLayout_49.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem27 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem27)
        self.cylHeightLabel_2 = QtWidgets.QLabel(self.spheEditPage)
        self.cylHeightLabel_2.setEnabled(False)
        self.cylHeightLabel_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylHeightLabel_2.setFont(font)
        self.cylHeightLabel_2.setObjectName("cylHeightLabel_2")
        self.horizontalLayout_29.addWidget(self.cylHeightLabel_2)
        self.cylHeightSlider_2 = QtWidgets.QSlider(self.spheEditPage)
        self.cylHeightSlider_2.setEnabled(False)
        self.cylHeightSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.cylHeightSlider_2.setObjectName("cylHeightSlider_2")
        self.horizontalLayout_29.addWidget(self.cylHeightSlider_2)
        self.cylHeightSpinner_2 = QtWidgets.QDoubleSpinBox(self.spheEditPage)
        self.cylHeightSpinner_2.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylHeightSpinner_2.setFont(font)
        self.cylHeightSpinner_2.setObjectName("cylHeightSpinner_2")
        self.horizontalLayout_29.addWidget(self.cylHeightSpinner_2)
        self.verticalLayout_49.addLayout(self.horizontalLayout_29)
        self.verticalLayout_48.addLayout(self.verticalLayout_49)
        self.verticalLayout_33.addLayout(self.verticalLayout_48)
        self.line_12 = QtWidgets.QFrame(self.spheEditPage)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_33.addWidget(self.line_12)
        self.NPMoveLabel_2 = QtWidgets.QLabel(self.spheEditPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.NPMoveLabel_2.setFont(font)
        self.NPMoveLabel_2.setObjectName("NPMoveLabel_2")
        self.verticalLayout_33.addWidget(self.NPMoveLabel_2)
        self.horizontalLayout_106 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_106.setObjectName("horizontalLayout_106")
        spacerItem28 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_106.addItem(spacerItem28)
        self.nonPerXLabel_2 = QtWidgets.QLabel(self.spheEditPage)
        self.nonPerXLabel_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonPerXLabel_2.sizePolicy().hasHeightForWidth())
        self.nonPerXLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.nonPerXLabel_2.setFont(font)
        self.nonPerXLabel_2.setObjectName("nonPerXLabel_2")
        self.horizontalLayout_106.addWidget(self.nonPerXLabel_2)
        self.nonPerX_2 = QtWidgets.QDoubleSpinBox(self.spheEditPage)
        self.nonPerX_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonPerX_2.sizePolicy().hasHeightForWidth())
        self.nonPerX_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.nonPerX_2.setFont(font)
        self.nonPerX_2.setObjectName("nonPerX_2")
        self.horizontalLayout_106.addWidget(self.nonPerX_2)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_106.addItem(spacerItem29)
        self.verticalLayout_33.addLayout(self.horizontalLayout_106)
        self.horizontalLayout_110 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_110.setObjectName("horizontalLayout_110")
        spacerItem30 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_110.addItem(spacerItem30)
        self.nonPerYLabel_2 = QtWidgets.QLabel(self.spheEditPage)
        self.nonPerYLabel_2.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.nonPerYLabel_2.setFont(font)
        self.nonPerYLabel_2.setObjectName("nonPerYLabel_2")
        self.horizontalLayout_110.addWidget(self.nonPerYLabel_2)
        self.nonPerY_2 = QtWidgets.QDoubleSpinBox(self.spheEditPage)
        self.nonPerY_2.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.nonPerY_2.setFont(font)
        self.nonPerY_2.setObjectName("nonPerY_2")
        self.horizontalLayout_110.addWidget(self.nonPerY_2)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_110.addItem(spacerItem31)
        self.verticalLayout_33.addLayout(self.horizontalLayout_110)
        self.horizontalLayout_113 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_113.setObjectName("horizontalLayout_113")
        spacerItem32 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_113.addItem(spacerItem32)
        self.nonPerZLabel_2 = QtWidgets.QLabel(self.spheEditPage)
        self.nonPerZLabel_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonPerZLabel_2.sizePolicy().hasHeightForWidth())
        self.nonPerZLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.nonPerZLabel_2.setFont(font)
        self.nonPerZLabel_2.setObjectName("nonPerZLabel_2")
        self.horizontalLayout_113.addWidget(self.nonPerZLabel_2)
        self.nonPerZ_2 = QtWidgets.QDoubleSpinBox(self.spheEditPage)
        self.nonPerZ_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonPerZ_2.sizePolicy().hasHeightForWidth())
        self.nonPerZ_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.nonPerZ_2.setFont(font)
        self.nonPerZ_2.setObjectName("nonPerZ_2")
        self.horizontalLayout_113.addWidget(self.nonPerZ_2)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_113.addItem(spacerItem33)
        self.verticalLayout_33.addLayout(self.horizontalLayout_113)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_33.addItem(spacerItem34)
        self.verticalLayout_29.addLayout(self.verticalLayout_33)
        self.sphereToolBox.addItem(self.spheEditPage, "")
        self.advPage = QtWidgets.QWidget()
        self.advPage.setGeometry(QtCore.QRect(0, 0, 293, 148))
        self.advPage.setObjectName("advPage")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.advPage)
        self.verticalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.sphereStack = QtWidgets.QStackedWidget(self.advPage)
        self.sphereStack.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        self.sphereStack.setFont(font)
        self.sphereStack.setObjectName("sphereStack")
        self.spheAdvPage_2 = QtWidgets.QWidget()
        self.spheAdvPage_2.setObjectName("spheAdvPage_2")
        self.horizontalLayout_116 = QtWidgets.QHBoxLayout(self.spheAdvPage_2)
        self.horizontalLayout_116.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_116.setObjectName("horizontalLayout_116")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.horizontalLayout_117 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_117.setObjectName("horizontalLayout_117")
        self.spheConstantLabel_6 = QtWidgets.QLabel(self.spheAdvPage_2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.spheConstantLabel_6.setFont(font)
        self.spheConstantLabel_6.setObjectName("spheConstantLabel_6")
        self.horizontalLayout_117.addWidget(self.spheConstantLabel_6)
        self.spheConstantDSpinBox_6 = QtWidgets.QDoubleSpinBox(self.spheAdvPage_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spheConstantDSpinBox_6.sizePolicy().hasHeightForWidth())
        self.spheConstantDSpinBox_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.spheConstantDSpinBox_6.setFont(font)
        self.spheConstantDSpinBox_6.setObjectName("spheConstantDSpinBox_6")
        self.horizontalLayout_117.addWidget(self.spheConstantDSpinBox_6)
        self.verticalLayout_51.addLayout(self.horizontalLayout_117)
        self.horizontalLayout_118 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_118.setObjectName("horizontalLayout_118")
        self.spheExpLabel_6 = QtWidgets.QLabel(self.spheAdvPage_2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.spheExpLabel_6.setFont(font)
        self.spheExpLabel_6.setObjectName("spheExpLabel_6")
        self.horizontalLayout_118.addWidget(self.spheExpLabel_6)
        self.spheExpSpinBox_6 = QtWidgets.QSpinBox(self.spheAdvPage_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spheExpSpinBox_6.sizePolicy().hasHeightForWidth())
        self.spheExpSpinBox_6.setSizePolicy(sizePolicy)
        self.spheExpSpinBox_6.setMinimumSize(QtCore.QSize(66, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.spheExpSpinBox_6.setFont(font)
        self.spheExpSpinBox_6.setMinimum(0)
        self.spheExpSpinBox_6.setMaximum(10)
        self.spheExpSpinBox_6.setSingleStep(2)
        self.spheExpSpinBox_6.setProperty("value", 2)
        self.spheExpSpinBox_6.setObjectName("spheExpSpinBox_6")
        self.horizontalLayout_118.addWidget(self.spheExpSpinBox_6)
        self.verticalLayout_51.addLayout(self.horizontalLayout_118)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_51.addItem(spacerItem35)
        self.horizontalLayout_116.addLayout(self.verticalLayout_51)
        self.sphereStack.addWidget(self.spheAdvPage_2)
        self.cylAdvancedPage_2 = QtWidgets.QWidget()
        self.cylAdvancedPage_2.setEnabled(False)
        self.cylAdvancedPage_2.setObjectName("cylAdvancedPage_2")
        self.horizontalLayout_119 = QtWidgets.QHBoxLayout(self.cylAdvancedPage_2)
        self.horizontalLayout_119.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_119.setSpacing(0)
        self.horizontalLayout_119.setObjectName("horizontalLayout_119")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.horizontalLayout_120 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_120.setObjectName("horizontalLayout_120")
        self.cylAlignLabel_2 = QtWidgets.QLabel(self.cylAdvancedPage_2)
        self.cylAlignLabel_2.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylAlignLabel_2.setFont(font)
        self.cylAlignLabel_2.setObjectName("cylAlignLabel_2")
        self.horizontalLayout_120.addWidget(self.cylAlignLabel_2)
        self.cylComboBox_2 = QtWidgets.QComboBox(self.cylAdvancedPage_2)
        self.cylComboBox_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cylComboBox_2.sizePolicy().hasHeightForWidth())
        self.cylComboBox_2.setSizePolicy(sizePolicy)
        self.cylComboBox_2.setMinimumSize(QtCore.QSize(66, 27))
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylComboBox_2.setFont(font)
        self.cylComboBox_2.setObjectName("cylComboBox_2")
        self.cylComboBox_2.addItem("")
        self.cylComboBox_2.addItem("")
        self.cylComboBox_2.addItem("")
        self.horizontalLayout_120.addWidget(self.cylComboBox_2)
        self.verticalLayout_52.addLayout(self.horizontalLayout_120)
        self.horizontalLayout_121 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_121.setObjectName("horizontalLayout_121")
        self.label_35 = QtWidgets.QLabel(self.cylAdvancedPage_2)
        self.label_35.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_121.addWidget(self.label_35)
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.cylAdvancedPage_2)
        self.doubleSpinBox_23.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_23.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.doubleSpinBox_23.setFont(font)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.horizontalLayout_121.addWidget(self.doubleSpinBox_23)
        self.verticalLayout_52.addLayout(self.horizontalLayout_121)
        self.horizontalLayout_122 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_122.setObjectName("horizontalLayout_122")
        self.cylConstantLabel_2 = QtWidgets.QLabel(self.cylAdvancedPage_2)
        self.cylConstantLabel_2.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylConstantLabel_2.setFont(font)
        self.cylConstantLabel_2.setObjectName("cylConstantLabel_2")
        self.horizontalLayout_122.addWidget(self.cylConstantLabel_2)
        self.cylConstantDSpinner_2 = QtWidgets.QDoubleSpinBox(self.cylAdvancedPage_2)
        self.cylConstantDSpinner_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cylConstantDSpinner_2.sizePolicy().hasHeightForWidth())
        self.cylConstantDSpinner_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylConstantDSpinner_2.setFont(font)
        self.cylConstantDSpinner_2.setObjectName("cylConstantDSpinner_2")
        self.horizontalLayout_122.addWidget(self.cylConstantDSpinner_2)
        self.verticalLayout_52.addLayout(self.horizontalLayout_122)
        self.horizontalLayout_123 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_123.setObjectName("horizontalLayout_123")
        self.cylExpLabel_2 = QtWidgets.QLabel(self.cylAdvancedPage_2)
        self.cylExpLabel_2.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylExpLabel_2.setFont(font)
        self.cylExpLabel_2.setObjectName("cylExpLabel_2")
        self.horizontalLayout_123.addWidget(self.cylExpLabel_2)
        self.cylExpSpinner_2 = QtWidgets.QSpinBox(self.cylAdvancedPage_2)
        self.cylExpSpinner_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cylExpSpinner_2.sizePolicy().hasHeightForWidth())
        self.cylExpSpinner_2.setSizePolicy(sizePolicy)
        self.cylExpSpinner_2.setMinimumSize(QtCore.QSize(66, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.cylExpSpinner_2.setFont(font)
        self.cylExpSpinner_2.setMinimum(0)
        self.cylExpSpinner_2.setMaximum(10)
        self.cylExpSpinner_2.setSingleStep(2)
        self.cylExpSpinner_2.setProperty("value", 2)
        self.cylExpSpinner_2.setObjectName("cylExpSpinner_2")
        self.horizontalLayout_123.addWidget(self.cylExpSpinner_2)
        self.verticalLayout_52.addLayout(self.horizontalLayout_123)
        spacerItem36 = QtWidgets.QSpacerItem(291, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_52.addItem(spacerItem36)
        self.horizontalLayout_119.addLayout(self.verticalLayout_52)
        self.sphereStack.addWidget(self.cylAdvancedPage_2)
        self.verticalLayout_50.addWidget(self.sphereStack)
        self.sphereToolBox.addItem(self.advPage, "")
        self.verticalLayout_26.addWidget(self.sphereToolBox)
        self.boundStackedWidget.addWidget(self.npPage)
        self.verticalLayout_5.addWidget(self.boundStackedWidget)
        self.line_2 = QtWidgets.QFrame(setupTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(setupTab)
        self.boundStackedWidget.setCurrentIndex(0)
        self.editToolbox.setCurrentIndex(0)
        self.solventComboBox.setCurrentIndex(0)
        self.sphereToolBox.setCurrentIndex(1)
        self.sphereStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(setupTab)

    def retranslateUi(self, setupTab):
        _translate = QtCore.QCoreApplication.translate
        setupTab.setWindowTitle(_translate("setupTab", "Dialog"))
        self.label_2.setText(_translate("setupTab", "Set boundary conditions"))
        self.boxBoundButton.setText(_translate("setupTab", "Periodic"))
        self.noneRButton.setText(_translate("setupTab", "None"))
        self.resizeLabel_3.setText(_translate("setupTab", "Resize"))
        self.ratioPCheckBox.setText(_translate("setupTab", "Keep aspect ratio"))
        self.equalCheckBox.setText(_translate("setupTab", "All equal"))
        self.lengthLabel_2.setText(_translate("setupTab", "Lx (Å):"))
        self.widthLabel_2.setText(_translate("setupTab", "Ly(Å):  "))
        self.heightLabel_2.setText(_translate("setupTab", "Lz (Å): "))
        self.movePerLabel_3.setText(_translate("setupTab", "Origin"))
        self.perXLabel_2.setText(_translate("setupTab", "X"))
        self.perYLabel_2.setText(_translate("setupTab", "Y"))
        self.perZLabel_2.setText(_translate("setupTab", "Z"))
        self.setMinBoxButton.setText(_translate("setupTab", "Set smallest box"))
        self.editToolbox.setItemText(self.editToolbox.indexOf(self.editBoxPage), _translate("setupTab", "Edit Box"))
        self.label_24.setText(_translate("setupTab", "Fill container with"))
        self.solventComboBox.setItemText(0, _translate("setupTab", "Water"))
        self.solventComboBox.setItemText(1, _translate("setupTab", "Acetone"))
        self.solventComboBox.setItemText(2, _translate("setupTab", "Chloroform"))
        self.solventComboBox.setItemText(3, _translate("setupTab", "Chloroform (4 atoms)"))
        self.solventComboBox.setItemText(4, _translate("setupTab", "THF"))
        self.solventComboBox.setItemText(5, _translate("setupTab", "Argon"))
        self.solventComboBox.setItemText(6, _translate("setupTab", "Selected Molecule"))
        self.label_18.setText(_translate("setupTab", "Solvent:"))
        self.label_23.setText(_translate("setupTab", "molecules"))
        self.label_12.setText(_translate("setupTab", "Density:"))
        self.label_19.setText(_translate("setupTab", "g/cm<sup>3</sup>"))
        self.label_20.setText(_translate("setupTab", "Volume"))
        self.volLineEdit.setToolTip(_translate("setupTab", "Volume of the box"))
        self.label_21.setText(_translate("setupTab", "nm<sup>3</sup>"))
        self.collisionsBox.setText(_translate("setupTab", "remove collisions"))
        self.replaceCheckBox.setText(_translate("setupTab", "replace collisions"))
        self.pcbBox.setText(_translate("setupTab", "Apply PBCs"))
        self.removeButton.setToolTip(_translate("setupTab", "Remove selected solvent"))
        self.removeButton.setText(_translate("setupTab", "Remove"))
        self.addButton.setToolTip(_translate("setupTab", "Add solvent"))
        self.addButton.setText(_translate("setupTab", "Add"))
        self.editToolbox.setItemText(self.editToolbox.indexOf(self.page_5), _translate("setupTab", "Solvate"))
        self.hydrogenBonding.setText(_translate("setupTab", "Hydrogen Bonding"))
        self.waterWrap.setText(_translate("setupTab", "Wrap water"))
        self.wrapAllMolecules.setText(_translate("setupTab", "Wrap all molecules"))
        self.editToolbox.setItemText(self.editToolbox.indexOf(self.advBoxPage), _translate("setupTab", "Advanced Settings"))
        self.label_5.setText(_translate("setupTab", "Shape"))
        self.spheRButton_2.setText(_translate("setupTab", "Spherical"))
        self.cylRButton_2.setText(_translate("setupTab", "Cylindrical"))
        self.NPResizeLabel_2.setText(_translate("setupTab", "Resize"))
        self.ratioNPCheckBox_2.setText(_translate("setupTab", "Keep aspect ratio"))
        self.centerLabel_2.setText(_translate("setupTab", "Center (Å):"))
        self.radiusLabel_2.setText(_translate("setupTab", "Radius (Å):"))
        self.cylHeightLabel_2.setText(_translate("setupTab", "Heigth (Å):"))
        self.NPMoveLabel_2.setText(_translate("setupTab", "Move By"))
        self.nonPerXLabel_2.setText(_translate("setupTab", "X"))
        self.nonPerYLabel_2.setText(_translate("setupTab", "Y"))
        self.nonPerZLabel_2.setText(_translate("setupTab", "Z"))
        self.sphereToolBox.setItemText(self.sphereToolBox.indexOf(self.spheEditPage), _translate("setupTab", "Edit Container"))
        self.spheConstantLabel_6.setText(_translate("setupTab", "Force Constant "))
        self.spheExpLabel_6.setText(_translate("setupTab", "Exponent"))
        self.cylAlignLabel_2.setText(_translate("setupTab", "Alignment"))
        self.cylComboBox_2.setItemText(0, _translate("setupTab", "X"))
        self.cylComboBox_2.setItemText(1, _translate("setupTab", "Y"))
        self.cylComboBox_2.setItemText(2, _translate("setupTab", "Z"))
        self.label_35.setText(_translate("setupTab", "TextLabel"))
        self.cylConstantLabel_2.setText(_translate("setupTab", "Force Constant "))
        self.cylExpLabel_2.setText(_translate("setupTab", "Exponent"))
        self.sphereToolBox.setItemText(self.sphereToolBox.indexOf(self.advPage), _translate("setupTab", "Advanced Settings"))

