# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wolffia.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Wolffia(object):
    def setupUi(self, Wolffia):
        Wolffia.setObjectName("Wolffia")
        Wolffia.resize(1080, 494)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Wolffia.sizePolicy().hasHeightForWidth())
        Wolffia.setSizePolicy(sizePolicy)
        Wolffia.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Wolffialogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Wolffia.setWindowIcon(icon)
        Wolffia.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Wolffia)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.forceTab = QtWidgets.QTabWidget(self.centralwidget)
        self.forceTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forceTab.sizePolicy().hasHeightForWidth())
        self.forceTab.setSizePolicy(sizePolicy)
        self.forceTab.setMinimumSize(QtCore.QSize(0, 0))
        self.forceTab.setBaseSize(QtCore.QSize(0, 0))
        self.forceTab.setToolTip("")
        self.forceTab.setStatusTip("")
        self.forceTab.setStyleSheet("QTabBar::tab {width: 120px; }")
        self.forceTab.setObjectName("forceTab")
        self.buildTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buildTab.sizePolicy().hasHeightForWidth())
        self.buildTab.setSizePolicy(sizePolicy)
        self.buildTab.setMinimumSize(QtCore.QSize(0, 0))
        self.buildTab.setObjectName("buildTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.buildTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.buildLayout = QtWidgets.QHBoxLayout()
        self.buildLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.buildLayout.setObjectName("buildLayout")
        self.gridLayout_8.addLayout(self.buildLayout, 0, 0, 1, 1)
        self.forceTab.addTab(self.buildTab, "")
        self.forceTab_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forceTab_2.sizePolicy().hasHeightForWidth())
        self.forceTab_2.setSizePolicy(sizePolicy)
        self.forceTab_2.setObjectName("forceTab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.forceTab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.forceLayout = QtWidgets.QHBoxLayout()
        self.forceLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.forceLayout.setObjectName("forceLayout")
        self.gridLayout_7.addLayout(self.forceLayout, 0, 0, 1, 1)
        self.forceTab.addTab(self.forceTab_2, "")
        self.setupTab = QtWidgets.QWidget()
        self.setupTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupTab.sizePolicy().hasHeightForWidth())
        self.setupTab.setSizePolicy(sizePolicy)
        self.setupTab.setObjectName("setupTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.setupTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.setupLayout = QtWidgets.QHBoxLayout()
        self.setupLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.setupLayout.setObjectName("setupLayout")
        self.gridLayout_6.addLayout(self.setupLayout, 0, 0, 1, 1)
        self.forceTab.addTab(self.setupTab, "")
        self.minimizeTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizeTab.sizePolicy().hasHeightForWidth())
        self.minimizeTab.setSizePolicy(sizePolicy)
        self.minimizeTab.setMinimumSize(QtCore.QSize(100, 100))
        self.minimizeTab.setObjectName("minimizeTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.minimizeTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.minTabLayout = QtWidgets.QHBoxLayout()
        self.minTabLayout.setObjectName("minTabLayout")
        self.gridLayout_5.addLayout(self.minTabLayout, 0, 0, 1, 1)
        self.forceTab.addTab(self.minimizeTab, "")
        self.simulationTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulationTab.sizePolicy().hasHeightForWidth())
        self.simulationTab.setSizePolicy(sizePolicy)
        self.simulationTab.setObjectName("simulationTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.simulationTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.simTabLayout = QtWidgets.QHBoxLayout()
        self.simTabLayout.setObjectName("simTabLayout")
        self.gridLayout_4.addLayout(self.simTabLayout, 0, 0, 1, 1)
        self.forceTab.addTab(self.simulationTab, "")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.analysisTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.analysisLayout = QtWidgets.QHBoxLayout()
        self.analysisLayout.setObjectName("analysisLayout")
        self.gridLayout_10.addLayout(self.analysisLayout, 0, 0, 1, 1)
        self.forceTab.addTab(self.analysisTab, "")
        self.verticalLayout.addWidget(self.forceTab)
        Wolffia.setCentralWidget(self.centralwidget)
        self.mainMenuBar = QtWidgets.QMenuBar(Wolffia)
        self.mainMenuBar.setEnabled(True)
        self.mainMenuBar.setGeometry(QtCore.QRect(0, 0, 1080, 30))
        self.mainMenuBar.setDefaultUp(True)
        self.mainMenuBar.setObjectName("mainMenuBar")
        self.menuFile = QtWidgets.QMenu(self.mainMenuBar)
        self.menuFile.setObjectName("menuFile")
        Wolffia.setMenuBar(self.mainMenuBar)
        self.statusBar = QtWidgets.QStatusBar(Wolffia)
        self.statusBar.setObjectName("statusBar")
        Wolffia.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(Wolffia)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        Wolffia.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtWidgets.QDockWidget(Wolffia)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(333, 299))
        self.dockWidget.setBaseSize(QtCore.QSize(100, 600))
        self.dockWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.FeedbackTabs = QtWidgets.QTabWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FeedbackTabs.sizePolicy().hasHeightForWidth())
        self.FeedbackTabs.setSizePolicy(sizePolicy)
        self.FeedbackTabs.setBaseSize(QtCore.QSize(400, 0))
        self.FeedbackTabs.setTabPosition(QtWidgets.QTabWidget.East)
        self.FeedbackTabs.setObjectName("FeedbackTabs")
        self.previewTab = QtWidgets.QWidget()
        self.previewTab.setObjectName("previewTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.previewTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.previewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setAcceptDrops(True)
        self.widget.setObjectName("widget")
        self.previewLayout = QtWidgets.QVBoxLayout(self.widget)
        self.previewLayout.setObjectName("previewLayout")
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.FeedbackTabs.addTab(self.previewTab, "")
        self.plotTab = QtWidgets.QWidget()
        self.plotTab.setObjectName("plotTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.plotTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.energyPlotsLayout = QtWidgets.QVBoxLayout()
        self.energyPlotsLayout.setObjectName("energyPlotsLayout")
        self.gridLayout_3.addLayout(self.energyPlotsLayout, 0, 0, 1, 1)
        self.FeedbackTabs.addTab(self.plotTab, "")
        self.jineticstab = QtWidgets.QWidget()
        self.jineticstab.setObjectName("jineticstab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.jineticstab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.kineticsPlotsLayuot = QtWidgets.QVBoxLayout()
        self.kineticsPlotsLayuot.setObjectName("kineticsPlotsLayuot")
        self.horizontalLayout.addLayout(self.kineticsPlotsLayuot)
        self.FeedbackTabs.addTab(self.jineticstab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.gridLayout = QtWidgets.QGridLayout(self.logTab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.messages = QtWidgets.QPlainTextEdit(self.logTab)
        self.messages.setObjectName("messages")
        self.verticalLayout_2.addWidget(self.messages)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.clearButton = QtWidgets.QPushButton(self.logTab)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_2.addWidget(self.clearButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.FeedbackTabs.addTab(self.logTab, "")
        self.gridLayout_9.addWidget(self.FeedbackTabs, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        Wolffia.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.resetButton = QtWidgets.QAction(Wolffia)
        self.resetButton.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.resetButton.setMenuRole(QtWidgets.QAction.NoRole)
        self.resetButton.setIconVisibleInMenu(True)
        self.resetButton.setObjectName("resetButton")
        self.undoButton = QtWidgets.QAction(Wolffia)
        self.undoButton.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.undoButton.setMenuRole(QtWidgets.QAction.NoRole)
        self.undoButton.setObjectName("undoButton")
        self.saveWFY = QtWidgets.QAction(Wolffia)
        self.saveWFY.setMenuRole(QtWidgets.QAction.NoRole)
        #self.saveWFY.setSoftKeyRole(QtWidgets.QAction.NoSoftKey)
        self.saveWFY.setObjectName("saveWFY")
        self.exitButton = QtWidgets.QAction(Wolffia)
        self.exitButton.setCheckable(False)
        self.exitButton.setAutoRepeat(False)
        self.exitButton.setMenuRole(QtWidgets.QAction.NoRole)
        self.exitButton.setObjectName("exitButton")
        self.redoButton = QtWidgets.QAction(Wolffia)
        self.redoButton.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.redoButton.setMenuRole(QtWidgets.QAction.NoRole)
        self.redoButton.setObjectName("redoButton")
        self.actionMixture = QtWidgets.QAction(Wolffia)
        self.actionMixture.setObjectName("actionMixture")
        self.actionLoad = QtWidgets.QAction(Wolffia)
        self.actionLoad.setObjectName("actionLoad")
        self.settingsButton = QtWidgets.QAction(Wolffia)
        self.settingsButton.setMenuRole(QtWidgets.QAction.NoRole)
        self.settingsButton.setObjectName("settingsButton")
        self.menuFile.addAction(self.resetButton)
        self.menuFile.addAction(self.undoButton)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.saveWFY)
        self.menuFile.addAction(self.exitButton)
        self.mainMenuBar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionMixture)
        self.toolBar.addAction(self.resetButton)
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.saveWFY)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.undoButton)
        self.toolBar.addAction(self.redoButton)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.settingsButton)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.exitButton)

        self.retranslateUi(Wolffia)
        self.forceTab.setCurrentIndex(0)
        self.FeedbackTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Wolffia)

    def retranslateUi(self, Wolffia):
        _translate = QtCore.QCoreApplication.translate
        Wolffia.setWindowTitle(_translate("Wolffia", "Wolffia"))
        self.forceTab.setTabText(self.forceTab.indexOf(self.buildTab), _translate("Wolffia", "1  Build"))
        self.forceTab.setTabToolTip(self.forceTab.indexOf(self.buildTab), _translate("Wolffia", "The Build Step"))
        self.forceTab.setTabText(self.forceTab.indexOf(self.forceTab_2), _translate("Wolffia", "2  Force Field"))
        self.forceTab.setTabToolTip(self.forceTab.indexOf(self.forceTab_2), _translate("Wolffia", "The Force Field Step"))
        self.forceTab.setTabText(self.forceTab.indexOf(self.setupTab), _translate("Wolffia", "3  Container"))
        self.forceTab.setTabToolTip(self.forceTab.indexOf(self.setupTab), _translate("Wolffia", "The Set-up Step"))
        self.forceTab.setTabText(self.forceTab.indexOf(self.minimizeTab), _translate("Wolffia", "4  Minimization"))
        self.forceTab.setTabToolTip(self.forceTab.indexOf(self.minimizeTab), _translate("Wolffia", "The Minimization Step"))
        self.forceTab.setTabText(self.forceTab.indexOf(self.simulationTab), _translate("Wolffia", "5  Simulation"))
        self.forceTab.setTabToolTip(self.forceTab.indexOf(self.simulationTab), _translate("Wolffia", "The Simulation Step"))
        self.forceTab.setTabText(self.forceTab.indexOf(self.analysisTab), _translate("Wolffia", "6 Analysis"))
        self.forceTab.setTabToolTip(self.forceTab.indexOf(self.analysisTab), _translate("Wolffia", "The Analysis Tab"))
        self.menuFile.setTitle(_translate("Wolffia", "File"))
        self.toolBar.setWindowTitle(_translate("Wolffia", "toolBar"))
        self.FeedbackTabs.setTabText(self.FeedbackTabs.indexOf(self.previewTab), _translate("Wolffia", "Preview"))
        self.FeedbackTabs.setTabText(self.FeedbackTabs.indexOf(self.plotTab), _translate("Wolffia", "Energy"))
        self.FeedbackTabs.setTabText(self.FeedbackTabs.indexOf(self.jineticstab), _translate("Wolffia", "Kinetics"))
        self.clearButton.setText(_translate("Wolffia", "Clear"))
        self.FeedbackTabs.setTabText(self.FeedbackTabs.indexOf(self.logTab), _translate("Wolffia", "Log"))
        self.resetButton.setText(_translate("Wolffia", " New"))
        self.resetButton.setIconText(_translate("Wolffia", "New"))
        self.resetButton.setToolTip(_translate("Wolffia", "Clear current simulation (CTRL- N)"))
        self.undoButton.setText(_translate("Wolffia", "Undo"))
        self.undoButton.setToolTip(_translate("Wolffia", "Undo (CTRL - U)"))
        self.undoButton.setShortcut(_translate("Wolffia", "Ctrl+U"))
        self.saveWFY.setText(_translate("Wolffia", "save simulation"))
        self.saveWFY.setIconText(_translate("Wolffia", "saveWFY"))
        self.saveWFY.setToolTip(_translate("Wolffia", "Save simulation"))
        self.saveWFY.setStatusTip(_translate("Wolffia", "Saves the simulation"))
        self.exitButton.setText(_translate("Wolffia", "Close"))
        self.redoButton.setText(_translate("Wolffia", "Redo"))
        self.redoButton.setToolTip(_translate("Wolffia", "Redo (CTRL - R)"))
        self.redoButton.setShortcut(_translate("Wolffia", "Ctrl+R"))
        self.actionMixture.setText(_translate("Wolffia", "Mixture"))
        self.actionMixture.setToolTip(_translate("Wolffia", "Create/delete simulations"))
        self.actionMixture.setShortcut(_translate("Wolffia", "Ctrl+N"))
        self.actionLoad.setText(_translate("Wolffia", "load"))
        self.actionLoad.setToolTip(_translate("Wolffia", "Load simulation"))
        self.settingsButton.setText(_translate("Wolffia", "settingsButton"))
        self.settingsButton.setToolTip(_translate("Wolffia", "settings"))

import Wolffia_icons_rc
