# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pedotSaveDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NanotubeSaveDialog(object):
    def setupUi(self, NanotubeSaveDialog):
        NanotubeSaveDialog.setObjectName("NanotubeSaveDialog")
        NanotubeSaveDialog.resize(400, 403)
        self.verticalLayoutWidget = QtWidgets.QWidget(NanotubeSaveDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman No9 L")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.browsePDBButton = QtWidgets.QPushButton(self.frame)
        self.browsePDBButton.setGeometry(QtCore.QRect(280, 30, 97, 27))
        self.browsePDBButton.setObjectName("browsePDBButton")
        self.pdbFilename = QtWidgets.QLineEdit(self.frame)
        self.pdbFilename.setGeometry(QtCore.QRect(30, 30, 211, 27))
        self.pdbFilename.setObjectName("pdbFilename")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 67, 17))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman No9 L")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 67, 17))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman No9 L")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.browsePSFButton = QtWidgets.QPushButton(self.frame_2)
        self.browsePSFButton.setGeometry(QtCore.QRect(280, 30, 97, 27))
        self.browsePSFButton.setObjectName("browsePSFButton")
        self.psfFilename = QtWidgets.QLineEdit(self.frame_2)
        self.psfFilename.setGeometry(QtCore.QRect(30, 30, 211, 27))
        self.psfFilename.setObjectName("psfFilename")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 371, 20))
        font = QtGui.QFont()
        font.setFamily("Nimbus Roman No9 L")
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NanotubeSaveDialog)
        QtCore.QMetaObject.connectSlotsByName(NanotubeSaveDialog)

    def retranslateUi(self, NanotubeSaveDialog):
        _translate = QtCore.QCoreApplication.translate
        NanotubeSaveDialog.setWindowTitle(_translate("NanotubeSaveDialog", "Save coordinates"))
        self.label.setText(_translate("NanotubeSaveDialog", "Save coordinates and topology"))
        self.browsePDBButton.setText(_translate("NanotubeSaveDialog", "Browse"))
        self.label_2.setText(_translate("NanotubeSaveDialog", "PDF file"))
        self.label_3.setText(_translate("NanotubeSaveDialog", "PSF file"))
        self.browsePSFButton.setText(_translate("NanotubeSaveDialog", "Browse"))
        self.label_4.setText(_translate("NanotubeSaveDialog", "(leaving this field empty inhibiths psf file generation)"))
        self.cancelButton.setText(_translate("NanotubeSaveDialog", "Cancel"))
        self.okButton.setText(_translate("NanotubeSaveDialog", "OK"))

